# Generated by Django 4.0.2 on 2022-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_db_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_data_from_db',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='NAME'),
        ),
    ]
